diffusion:
  cfg_path: configs/guided_diffusion/diffusion_celeba_256.yaml
  resume_path: pretrained_ckpt/celeba_hq.ckpt


sample:
  use_ddim: true
  ddim_eta: 0.8
  img_size: 256

datasets:
  test:
    target: trainer.dataset.Dataset.ImageDataset
    params:
      gt_root: data_demo/dataset/celeba/*.png
      img_size: 256
      mask_root: ~

dataloader:
  test:
    batch_size: 1
    num_workers: 1